# Generated by Django 5.1.4 on 2024-12-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_turnos', '0004_asignacionnotificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='guardia',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='sucursal',
        ),
        migrations.DeleteModel(
            name='Disponibilidad',
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
